image: docker:20

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --tag $CI_REGISTRY_IMAGE:latest --file Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
